#!/bin/bash

# Check root
[[ $EUID -ne 0 ]] && echo "Run as root" && exit 1

# Clone repo
rm -rf /tmp/grub
git clone https://github.com/madhur-dhama/my-grub-themes.git /tmp/grub --quiet

# List themes
echo "Available themes:"
themes=($(ls /tmp/grub/))
for i in "${!themes[@]}"; do
  echo "$((i + 1))) ${themes[i]}"
done

# Select theme
read -p "Select theme (1-${#themes[@]}): " choice
selected="${themes[$((choice - 1))]}"

# Backup grub config
cp /etc/default/grub /etc/default/grub.bak.$(date +%Y%m%d_%H%M%S)

# Install theme
mkdir -p /boot/grub/themes
cp -r /tmp/grub/"$selected" /boot/grub/themes/

# Update grub config
sed -i '/^#*GRUB_THEME=/d' /etc/default/grub
echo "GRUB_THEME=\"/boot/grub/themes/$selected/theme.txt\"" >>/etc/default/grub

# Update grub
grub-mkconfig -o /boot/grub/grub.cfg

# Cleanup
rm -rf /tmp/grub

echo "Theme '$selected' installed. Reboot to see changes."
